language: python
python:
  - 3.8
install:
  - pip install pylint
  - pip install -r requirements.txt
script:
  - pylint --fail-under=9.00 labdevices tests
  - python -m unittest tests -k DummyTest
  - python -m unittest tests.test_interface